trigger:
- main   # runs when you push to main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: pytest
  displayName: 'Run tests'